FROM rust:1.70-slim as builder

# Create a new empty shell project
WORKDIR /app
RUN apt-get update && apt-get install -y protobuf-compiler

# Copy manifests
COPY ./secrets-service-rs/Cargo.toml ./secrets-service-rs/Cargo.toml
COPY ./Cargo.toml ./Cargo.toml
COPY ./.proto ./.proto

# Build empty project to cache dependencies
WORKDIR /app/secrets-service-rs
RUN mkdir src && echo 'fn main() { println!("Dummy!"); }' > src/main.rs
RUN cargo build

# Copy actual source code
COPY ./secrets-service-rs/src ./src
COPY ./secrets-service-rs/build.rs ./build.rs

# Build for release
RUN cargo build --release

# Final stage
FROM debian:bullseye-slim
RUN apt-get update && apt-get install -y ca-certificates && rm -rf /var/lib/apt/lists/*

WORKDIR /app
COPY --from=builder /app/target/release/secrets-service-rs /app/secrets-service-rs

# Expose the port
EXPOSE 50080

# Run the service
CMD ["./secrets-service-rs"]